### ISSUE TITLE
Whenever i try to login with a customer account i get internal server error

### ISSUE THREAD

**Issue by harshit-simplifytechin** [wp-graphql/wp-graphql-jwt-authentication#101]
hello, I am on the latest develop branch and whenever i try to use login mutation with Customer login details, it says internal server error. Am i missing something ? Subscriber user role works just fine, don't know why this is happening here

**Comment by PlusA2M** [comment]
Hi, I think you need to provide more information for us to diagnose you issue. How's your query being processed and what's in the headers & body? For example, when you try to login with authorization header, it will throw 500 error.

**Comment by vashisth00** [comment]
I get the same issue earlier just using WP-GraphQL was working fine for me to fetch posts and show them but adding this is causing Internal Server Error

**Comment by lengieng** [comment]
Try enabling the **GraphQL Debug Mode** and see what the `debugMessage` is.

In my case, the `debugMessage` is `Cookie nonce is invalid`. Looks like I can't test loggin in another user via GraphiQL IDE.

To fix this in my case, I tested logging in another user on the Postman instead, and it worked there. No issue.

<img width="389" alt="Screen Shot 2020-12-14 at 11 49 34 AM" src="https://user-images.githubusercontent.com/1238061/102104659-d63c4f00-3e04-11eb-8929-9e522881a384.png">

**Comment by SukhorukovS** [comment]
Hello I've got an Internal Server Error, while login from my local machine. But if I try to do a mutation in Graphiql IDE all work fine.
here is mutation
![image](https://user-images.githubusercontent.com/28947824/179393442-3fa119f6-3eda-4260-b6b6-95e12b4153f3.png)
Authorization header is not provided
Here is a stack trace
```[Sun Jul 17 12:52:23 2022] [error] [pid 30937] sapi_apache2.c(362): [client 2.93.205.174:36784] PHP Fatal error:  Uncaught TypeError: Argument 3 passed to WPGraphQL\\Router::prepare_headers() must be of the type string, array given, called in /home/c/cp53703/wordpress_3/public_html/wp-content/plugins/wp-graphql/src/Router.php on line 501 and defined in /home/c/cp53703/wordpress_3/public_html/wp-content/plugins/wp-graphql/src/Router.php:541\nStack trace:\n#0 /home/c/cp53703/wordpress_3/public_html/wp-content/plugins/wp-graphql/src/Router.php(501): WPGraphQL\\Router::prepare_headers(Object(GraphQL\\Executor\\ExecutionResult), Object(GraphQL\\Executor\\ExecutionResult), Array, '', NULL)\n#1 /home/c/cp53703/wordpress_3/public_html/wp-content/plugins/wp-graphql/src/Router.php(265): WPGraphQL\\Router::process_http_request()\n#2 /home/c/cp53703/wordpress_3/public_html/wp-includes/class-wp-hook.php(287): WPGraphQL\\Router->resolve_http_request(Object(WP))\n#3 /home/c/cp53703/wordpress_3/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)\n#4 /home/c/cp53703/wordpress_3/public_html/wp-includes/plugin.php(544): W in /home/c/cp53703/wordpress_3/public_html/wp-content/plugins/wp-graphql/src/Router.php on line 541```
What am I doing wrong, please help
