### ISSUE TITLE
codecept_debug is alive in Auth.php

### ISSUE THREAD

**Issue by devsunssc** [wp-graphql/wp-graphql-jwt-authentication#157]
codecept_debug is alive in Auth.php

**Comment by tke849** [comment]
This is also preventing us from successful authentication. Commenting out this line allows authentication to work, but this only allows us to be successful in a  local setup. We do not want to edit our production plugins...

**Comment by gilzow** [comment]
ditto. Running into the exact same issue when attempting to pass in an `Authorization` header with the refresh token obtained via `LoginUser` mutation. From the logs:
```php
<b>Fatal error</b>:  Uncaught Error: Call to undefined function WPGraphQL\JWT_Authentication\codecept_debug() in /app/wordpress/wp-content/plugins/wp-graphql-jwt-authentication/src/Auth.php:587
Stack trace:
#0 /app/wordpress/wp-content/plugins/wp-graphql-jwt-authentication/src/Auth.php(406): WPGraphQL\JWT_Authentication\Auth::validate_token()
#1 /app/wordpress/wp-includes/class-wp-hook.php(307): WPGraphQL\JWT_Authentication\Auth::filter_determine_current_user(false)
#2 /app/wordpress/wp-includes/plugin.php(189): WP_Hook-&gt;apply_filters(false, Array)
#3 /app/wordpress/wp-includes/user.php(3373): apply_filters('determine_curre...', false)
#4 /app/wordpress/wp-includes/pluggable.php(70): _wp_get_current_user()
#5 /app/wordpress/wp-includes/class-wp.php(624): wp_get_current_user()
#6 /app/wordpress/wp-settings.php(574): WP-&gt;init()
#7 /app/wordpress/wp-config.php(131): require_once('/app/wordpress/...')
#8 /app/wordpress/wp-load.php(50): require_once('/app/wordpress/...')
#9 /app/wordpress/wp-blog-header.php(13): require_once('/app/wor in <b>/app/wordpress/wp-content/plugins/wp-graphql-jwt-authentication/src/Auth.php</b> on line <b>587</b><br />
```
